### ISSUE TITLE
Implement post_save hook to mirror django.contrib.admin.models.LogEntry

### ISSUE THREAD

**Issue by sergei-maertens** [maykinmedia/django-timeline-logger#21]
From open-formulieren/open-forms#2352 it's clear that `LogEntry` records are cascade-deleted when the user is deleted.

To not risk losing audit trails (one of the main reasons this library is often used), we should ensure that all admin `LogEntry` records are _copied_ to timeline logger - this can be done with a `post_save` signal. It's important that we then also serialize the user representation (`str(user)`, if given) into the JSON field data so this can still be retrieved when the user account is deleted (by accident or malicious intent).

This behaviour should be opt-in through a setting: `TIMELINE_MIRROR_ADMIN_LOGENTRY = False`.

**Tasks**

* [ ] Set up post save signal
* [ ] Implement/support templates for Django's action types if needed https://github.com/django/django/blob/main/django/contrib/admin/models.py#L17
* [ ] See if we can leverage the change_message logic: https://github.com/django/django/blob/main/django/contrib/admin/models.py#L109
* [ ] Ensure our log records are linked to the same object (https://github.com/django/django/blob/main/django/contrib/admin/models.py#L66)
* [ ] Ensure our log records are not deleted when the user is deleted
